name: Deploy Staging (Fresh Database Seeded)
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch or SHA to deploy'
        required: true
        default: 'development'
      deploytype:
        type: choice
        description: 'Type of Deploy'
        options:
          - branch
          - sha
        required: true
        default: branch
      server:
        type: choice
        required: true
        description: Select a Staging Server to Deploy to/n Mochi@8.0
        options:
          - Mochi@8.0
          - Zelda@8.0
          - Cora@8.1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event.inputs.server == 'Mochi@8.0' }}
        run: echo "Its Mochi@8.0"
      - if: ${{ github.event.inputs.server == 'Zelda@8.0' }}
        run: echo "Its Zelda@8.0"
      - if: ${{ github.event.inputs.server == 'Cora@8.0' }}
        run: echo "Its Cora@8.0"
      - if: ${{ github.event.inputs.server == 'Zeldaaaaa@8.0' }}
        run: curl ${{ secrets.ENVOYER_TURTLE_HOOK }}?${{ github.event.inputs.deploytype }}=${{ github.event.inputs.branch }}
